$(document).ready(function(){
    $("#home").click(function(){
      $("#aboutme").hide();
      $("#contact-box").hide();
    });
    $("#about").click(function(){
      $("#aboutme").show();
      $("#contact-box").hide();
    });
    $("#contact").click(function(){
      $("#aboutme").hide();
      $("#contact-box").show();
    });
    $("#menu").click(function(){
      $("#home").toggle();
      $("#about").toggle();
      $("#contact").toggle();
    });
    $("#external-toggle").click(function(){
      $("#github").toggle();
      $("#linkdin").toggle();
    });
});
