$(document).ready(function(){
    $("#home").click(function(){
      $("#aboutme").hide();
      $("#contact-box").hide();
    });
    $("#about").click(function(){
      $("#aboutme").show();
      $("#contact-box").hide();
    });
    $("#contact").click(function(){
      $("#aboutme").hide();
      $("#contact-box").show();
    });
  });
